name: Deploy to GCP Cloud Run

on:
  push:
    branches:
      - master

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: us-east1
  SERVICE: bcp-webapp
  IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/bcp-webapp

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v6

      - name: Autenticar no Google Cloud
        uses: google-github-actions/auth@v3
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v3

      - name: Autorizar envio para o Docker
        run: gcloud auth configure-docker gcr.io

      - name: Compilar e Enviar o Container
        run: |-
          docker build -t ${{ env.IMAGE_NAME }}:${{ github.sha }} .
          docker push ${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v3
        with:
          service: '${{ env.SERVICE }}'
          region: '${{ env.REGION }}'
          image: '${{ env.IMAGE_NAME }}:${{ github.sha }}'
          env_vars: |-
            ASPNETCORE_ENVIRONMENT=Production
            ConnectionStrings__DefaultConnection=${{ secrets.DB_CONNECTION_STRING }}
          flags: '--allow-unauthenticated'